apiVersion: v1
kind: Service
metadata:
  name: socket-server
  labels:
    app: socket-server
spec:
  selector:
    app: socket-server
  ports:
    - name: socket
      port: 4001
      targetPort: socket-port
  type: ClusterIP
  sessionAffinity: None