apiVersion: v1
kind: Secret
metadata:
  name: smoothie-secrets
  namespace: smoothie
  labels:
    app.kubernetes.io/name: smoothie-secrets
    app.kubernetes.io/part-of: smoothie-stack
stringData:
  NUXT_SESSION_PASSWORD: dcff9cbd376f460eae588f39dda3a462
