apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smoothie
resources:
  - namespace.yaml
  - app-configmap.yaml
  - app-secret.yaml
  - redis.yaml
  - mongodb.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-ingress.yaml
  - seed-job.yaml
